name: Vagrant CMake

on: [push, pull_request]

jobs:
  # Only macos runner provide virtualisation with vagrant/virtualbox installed.
  FreeBSD:
    runs-on: macos-latest
    strategy:
      matrix:
        distro: [freebsd]
        lang: [cpp, python, dotnet, java]
      fail-fast: false
    env:
      DISTRO: ${{ matrix.distro }}
      LANG: ${{ matrix.lang }}
    steps:
    - uses: actions/checkout@v2
    - name: vagrant version
      run: Vagrant --version
    - name: VirtualBox version
      run: virtualbox -h
    - name: Build
      run: make --directory=cmake ${DISTRO}_${LANG}
